SURAH_LIST = [
    {"id": 1, "name_ar": "الفاتحة", "name_en": "Al-Fatihah", "name_so": "Al-Faatixah"},
    {"id": 2, "name_ar": "البقرة", "name_en": "Al-Baqarah", "name_so": "Al-Baqarah"},
    {"id": 3, "name_ar": "آل عمران", "name_en": "Aal-e-Imran", "name_so": "Aala Cimraan"},
    {"id": 4, "name_ar": "النساء", "name_en": "An-Nisa", "name_so": "An-Nisaa"},
    {"id": 5, "name_ar": "المائدة", "name_en": "Al-Ma'idah", "name_so": "Al-Maa'idah"},
    {"id": 6, "name_ar": "الأنعام", "name_en": "Al-An'am", "name_so": "Al-Ancaam"},
    {"id": 7, "name_ar": "الأعراف", "name_en": "Al-A'raf", "name_so": "Al-Acraaf"},
    {"id": 8, "name_ar": "الأنفال", "name_en": "Al-Anfal", "name_so": "Al-Anfaal"},
    {"id": 9, "name_ar": "التوبة", "name_en": "At-Tawbah", "name_so": "At-Tawbah"},
    {"id": 10, "name_ar": "يونس", "name_en": "Yunus", "name_so": "Yuunus"},
    {"id": 11, "name_ar": "هود", "name_en": "Hud", "name_so": "Huud"},
    {"id": 12, "name_ar": "يوسف", "name_en": "Yusuf", "name_so": "Yuusuf"},
    {"id": 13, "name_ar": "الرعد", "name_en": "Ar-Ra'd", "name_so": "Ar-Racd"},
    {"id": 14, "name_ar": "إبراهيم", "name_en": "Ibrahim", "name_so": "Ibraahiim"},
    {"id": 15, "name_ar": "الحجر", "name_en": "Al-Hijr", "name_so": "Al-Xijr"},
    {"id": 16, "name_ar": "النحل", "name_en": "An-Nahl", "name_so": "An-Naxl"},
    {"id": 17, "name_ar": "الإسراء", "name_en": "Al-Isra", "name_so": "Al-Israa"},
    {"id": 18, "name_ar": "الكهف", "name_en": "Al-Kahf", "name_so": "Al-Kahf"},
    {"id": 19, "name_ar": "مريم", "name_en": "Maryam", "name_so": "Maryam"},
    {"id": 20, "name_ar": "طه", "name_en": "Taha", "name_so": "Daahaa"},
    {"id": 21, "name_ar": "الأنبياء", "name_en": "Al-Anbiya", "name_so": "Al-Anbiyaa"},
    {"id": 22, "name_ar": "الحج", "name_en": "Al-Hajj", "name_so": "Al-Xajj"},
    {"id": 23, "name_ar": "المؤمنون", "name_en": "Al-Mu'minun", "name_so": "Al-Muuminuun"},
    {"id": 24, "name_ar": "النور", "name_en": "An-Nur", "name_so": "An-Nuur"},
    {"id": 25, "name_ar": "الفرقان", "name_en": "Al-Furqan", "name_so": "Al-Furqaan"},
    {"id": 26, "name_ar": "الشعراء", "name_en": "Ash-Shu'ara", "name_so": "Ash-Shucaraa"},
    {"id": 27, "name_ar": "النمل", "name_en": "An-Naml", "name_so": "An-Naml"},
    {"id": 28, "name_ar": "القصص", "name_en": "Al-Qasas", "name_so": "Al-Qasas"},
    {"id": 29, "name_ar": "العنكبوت", "name_en": "Al-Ankabut", "name_so": "Al-Cankabuut"},
    {"id": 30, "name_ar": "الروم", "name_en": "Ar-Rum", "name_so": "Ar-Ruum"},
    {"id": 31, "name_ar": "لقمان", "name_en": "Luqman", "name_so": "Luqmaan"},
    {"id": 32, "name_ar": "السجدة", "name_en": "As-Sajdah", "name_so": "As-Sajdah"},
    {"id": 33, "name_ar": "الأحزاب", "name_en": "Al-Ahzab", "name_so": "Al-Axzaab"},
    {"id": 34, "name_ar": "سبأ", "name_en": "Saba", "name_so": "Saba"},
    {"id": 35, "name_ar": "فاطر", "name_en": "Fatir", "name_so": "Faadir"},
    {"id": 36, "name_ar": "يس", "name_en": "Ya-Sin", "name_so": "Yaasiin"},
    {"id": 37, "name_ar": "الصافات", "name_en": "As-Saffat", "name_so": "As-Saaffaat"},
    {"id": 38, "name_ar": "ص", "name_en": "Sad", "name_so": "Saad"},
    {"id": 39, "name_ar": "الزمر", "name_en": "Az-Zumar", "name_so": "Az-Zumar"},
    {"id": 40, "name_ar": "غافر", "name_en": "Ghafir", "name_so": "Ghaafir"},
    {"id": 41, "name_ar": "فصلت", "name_en": "Fussilat", "name_so": "Fussilat"},
    {"id": 42, "name_ar": "الشورى", "name_en": "Ash-Shura", "name_so": "Ash-Shuuraa"},
    {"id": 43, "name_ar": "الزخرف", "name_en": "Az-Zukhruf", "name_so": "Az-Zukhruf"},
    {"id": 44, "name_ar": "الدخان", "name_en": "Ad-Dukhan", "name_so": "Ad-Dukhaan"},
    {"id": 45, "name_ar": "الجاثية", "name_en": "Al-Jathiyah", "name_so": "Al-Jaasiyah"},
    {"id": 46, "name_ar": "الأحقاف", "name_en": "Al-Ahqaf", "name_so": "Al-Axqaaf"},
    {"id": 47, "name_ar": "محمد", "name_en": "Muhammad", "name_so": "Maxamed"},
    {"id": 48, "name_ar": "الفتح", "name_en": "Al-Fath", "name_so": "Al-Fatx"},
    {"id": 49, "name_ar": "الحجرات", "name_en": "Al-Hujurat", "name_so": "Al-Xujuraat"},
    {"id": 50, "name_ar": "ق", "name_en": "Qaf", "name_so": "Qaaf"},
    {"id": 51, "name_ar": "الذاريات", "name_en": "Ad-Dhariyat", "name_so": "Ad-Daariyaat"},
    {"id": 52, "name_ar": "الطور", "name_en": "At-Tur", "name_so": "Ad-Duur"},
    {"id": 53, "name_ar": "النجم", "name_en": "An-Najm", "name_so": "An-Najm"},
    {"id": 54, "name_ar": "القمر", "name_en": "Al-Qamar", "name_so": "Al-Qamar"},
    {"id": 55, "name_ar": "الرحمن", "name_en": "Ar-Rahman", "name_so": "Ar-Raxmaan"},
    {"id": 56, "name_ar": "الواقعة", "name_en": "Al-Waqi'ah", "name_so": "Al-Waaqicah"},
    {"id": 57, "name_ar": "الحديد", "name_en": "Al-Hadid", "name_so": "Al-Xadiid"},
    {"id": 58, "name_ar": "المجادلة", "name_en": "Al-Mujadila", "name_so": "Al-Mujaadalah"},
    {"id": 59, "name_ar": "الحشر", "name_en": "Al-Hashr", "name_so": "Al-Xashr"},
    {"id": 60, "name_ar": "الممتحنة", "name_en": "Al-Mumtahanah", "name_so": "Al-Mumtaxanah"},
    {"id": 61, "name_ar": "الصف", "name_en": "As-Saff", "name_so": "As-Saf"},
    {"id": 62, "name_ar": "الجمعة", "name_en": "Al-Jumu'ah", "name_so": "Al-Jumucah"},
    {"id": 63, "name_ar": "المنافقون", "name_en": "Al-Munafiqun", "name_so": "Al-Munaafiquun"},
    {"id": 64, "name_ar": "التغابن", "name_en": "At-Taghabun", "name_so": "At-Taghaabun"},
    {"id": 65, "name_ar": "الطلاق", "name_en": "At-Talaq", "name_so": "Ad-Dalaaq"},
    {"id": 66, "name_ar": "التحريم", "name_en": "At-Tahrim", "name_so": "At-Taxriim"},
    {"id": 67, "name_ar": "الملك", "name_en": "Al-Mulk", "name_so": "Al-Mulk"},
    {"id": 68, "name_ar": "القلم", "name_en": "Al-Qalam", "name_so": "Al-Qalam"},
    {"id": 69, "name_ar": "الحاقة", "name_en": "Al-Haqqah", "name_so": "Al-Xaaqqah"},
    {"id": 70, "name_ar": "المعارج", "name_en": "Al-Ma'arij", "name_so": "Al-Macaarij"},
    {"id": 71, "name_ar": "نوح", "name_en": "Nuh", "name_so": "Nuux"},
    {"id": 72, "name_ar": "الجن", "name_en": "Al-Jinn", "name_so": "Al-Jin"},
    {"id": 73, "name_ar": "المزمل", "name_en": "Al-Muzzammil", "name_so": "Al-Muzzammil"},
    {"id": 74, "name_ar": "المدثر", "name_en": "Al-Muddaththir", "name_so": "Al-Muddassir"},
    {"id": 75, "name_ar": "القيامة", "name_en": "Al-Qiyamah", "name_so": "Al-Qiyaamah"},
    {"id": 76, "name_ar": "الإنسان", "name_en": "Al-Insan", "name_so": "Al-Insaan"},
    {"id": 77, "name_ar": "المرسلات", "name_en": "Al-Mursalat", "name_so": "Al-Mursalaat"},
    {"id": 78, "name_ar": "النبأ", "name_en": "An-Naba", "name_so": "An-Naba"},
    {"id": 79, "name_ar": "النازعات", "name_en": "An-Nazi'at", "name_so": "An-Naazicaat"},
    {"id": 80, "name_ar": "عبس", "name_en": "Abasa", "name_so": "Cabasa"},
    {"id": 81, "name_ar": "التكوير", "name_en": "At-Takwir", "name_so": "At-Takwiir"},
    {"id": 82, "name_ar": "الانفطار", "name_en": "Al-Infitar", "name_so": "Al-Infidaar"},
    {"id": 83, "name_ar": "المطففين", "name_en": "Al-Mutaffifin", "name_so": "Al-Mudaffifiin"},
    {"id": 84, "name_ar": "الانشقاق", "name_en": "Al-Inshiqaq", "name_so": "Al-Inshiqaaq"},
    {"id": 85, "name_ar": "البروج", "name_en": "Al-Buruj", "name_so": "Al-Buruuj"},
    {"id": 86, "name_ar": "الطارق", "name_en": "At-Tariq", "name_so": "Ad-Daariq"},
    {"id": 87, "name_ar": "الأعلى", "name_en": "Al-A'la", "name_so": "Al-Aclaa"},
    {"id": 88, "name_ar": "الغاشية", "name_en": "Al-Ghashiyah", "name_so": "Al-Ghaashiyah"},
    {"id": 89, "name_ar": "الفجر", "name_en": "Al-Fajr", "name_so": "Al-Fajr"},
    {"id": 90, "name_ar": "البلد", "name_en": "Al-Balad", "name_so": "Al-Balad"},
    {"id": 91, "name_ar": "الشمس", "name_en": "Ash-Shams", "name_so": "Ash-Shams"},
    {"id": 92, "name_ar": "الليل", "name_en": "Al-Layl", "name_so": "Al-Layl"},
    {"id": 93, "name_ar": "الضحى", "name_en": "Ad-Duha", "name_so": "Ad-Duxaa"},
    {"id": 94, "name_ar": "الشرح", "name_en": "Ash-Sharh", "name_so": "Ash-Sharx"},
    {"id": 95, "name_ar": "التين", "name_en": "At-Tin", "name_so": "At-Tiin"},
    {"id": 96, "name_ar": "العلق", "name_en": "Al-Alaq", "name_so": "Al-Calaq"},
    {"id": 97, "name_ar": "القدر", "name_en": "Al-Qadr", "name_so": "Al-Qadr"},
    {"id": 98, "name_ar": "البينة", "name_en": "Al-Bayyinah", "name_so": "Al-Bayyinah"},
    {"id": 99, "name_ar": "الزلزلة", "name_en": "Az-Zalzalah", "name_so": "Az-Zalzalah"},
    {"id": 100, "name_ar": "العاديات", "name_en": "Al-Adiyat", "name_so": "Al-Caadiyaat"},
    {"id": 101, "name_ar": "القارعة", "name_en": "Al-Qari'ah", "name_so": "Al-Qaaricah"},
    {"id": 102, "name_ar": "التكاثر", "name_en": "At-Takathur", "name_so": "At-Takaasur"},
    {"id": 103, "name_ar": "العصر", "name_en": "Al-Asr", "name_so": "Al-Casr"},
    {"id": 104, "name_ar": "الهمزة", "name_en": "Al-Humazah", "name_so": "Al-Xumazah"},
    {"id": 105, "name_ar": "الفيل", "name_en": "Al-Fil", "name_so": "Al-Fiil"},
    {"id": 106, "name_ar": "قريش", "name_en": "Quraysh", "name_so": "Quraysh"},
    {"id": 107, "name_ar": "الماعون", "name_en": "Al-Ma'un", "name_so": "Al-Maacuun"},
    {"id": 108, "name_ar": "الكوثر", "name_en": "Al-Kawthar", "name_so": "Al-Kawsar"},
    {"id": 109, "name_ar": "الكافرون", "name_en": "Al-Kafirun", "name_so": "Al-Kaafiruun"},
    {"id": 110, "name_ar": "النصر", "name_en": "An-Nasr", "name_so": "An-Nasr"},
    {"id": 111, "name_ar": "المسد", "name_en": "Al-Masad", "name_so": "Al-Masad"},
    {"id": 112, "name_ar": "الإخلاص", "name_en": "Al-Ikhlas", "name_so": "Al-Ikhlaas"},
    {"id": 113, "name_ar": "الفلق", "name_en": "Al-Falaq", "name_so": "Al-Falaq"},
    {"id": 114, "name_ar": "الناس", "name_en": "An-Nas", "name_so": "An-Naas"}
]

def find_surah_meta(filename_or_key: str):
    # Try to extract ID from filename pattern like "Al-Faatixah (1)" or "Surah 1"
    import re
    match = re.search(r'\((\d+)\)', filename_or_key) or re.search(r'\b(\d+)\b', filename_or_key)
    if match:
        surah_id = int(match.group(1))
        for s in SURAH_LIST:
            if s["id"] == surah_id:
                return s
                
    # Fallback to string matching
    key_lower = filename_or_key.lower()
    for s in SURAH_LIST:
        if s["name_en"].lower() in key_lower or s["name_so"].lower() in key_lower:
            return s
            
    # Default fallback
    return {
        "id": None,
        "name_ar": filename_or_key,
        "name_en": filename_or_key,
        "name_so": filename_or_key
    }
